services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: quickpoll
      POSTGRES_USER: quickpoll
      POSTGRES_PASSWORD: quickpoll
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U quickpoll"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/quickpoll
      - SPRING_DATASOURCE_USERNAME=quickpoll
      - SPRING_DATASOURCE_PASSWORD=quickpoll
      - JAVA_OPTS=-Xms256m -Xmx512m
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/polls"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  db_data: