services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: quickpoll
      POSTGRES_USER: quickpoll
      POSTGRES_PASSWORD: quickpoll
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U quickpoll"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - backend-net

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/quickpoll
      - SPRING_DATASOURCE_USERNAME=quickpoll
      - SPRING_DATASOURCE_PASSWORD=quickpoll
      - JAVA_OPTS=-Xms256m -Xmx512m
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/polls"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - backend-net

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      backend:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - backend-net

  # frontend:
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile
  #   environment:
  #     - NEXT_PUBLIC_API_URL=http://backend:8080/api
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     backend:
  #       condition: service_healthy

volumes:
  db_data:

networks:
  backend-net:
    driver: bridge