spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/quickpoll
    username: quickpoll
    password: quickpoll
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
    show-sql: true
    open-in-view: false
  flyway:
    enabled: true
    baseline-on-migrate: true

server:
  port: 8080
  servlet:
    context-path: /api

logging:
  level:
    com.example.demo.quickpoll: DEBUG
    org.hibernate.SQL: DEBUG